MovieManagement/MovieManagementApp/MovieCruiserApp/Controllers/AnonymousController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using MovieCruiserApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace MovieCruiserApp.Controllers
{
    public class AnonymousController : Controller
    {
        public async Task<IActionResult> Index()
        {

                List<MovieItem> ItemList = new List<MovieItem>();
                using (var client = new HttpClient())
                {


                    var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                    client.DefaultRequestHeaders.Accept.Add(contentType);


                    using (var response = await client.GetAsync("https://localhost:44395/api/anonymoususer/"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        ItemList = JsonConvert.DeserializeObject<List<MovieItem>>(apiResponse);
                    }
                using (var response = await client.GetAsync("https://localhost:44395/api/anonymoususer/Genres"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Genres = JsonConvert.DeserializeObject<List<Genre>>(apiResponse).ToList();
                }
            }
                return View(ItemList);
            
        }
    }
}

MovieManagement/MovieManagementApp/MovieCruiserApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using MovieCruiserApp.Models;

namespace MovieCruiserApp.Controllers
{
    public class CustomerController : Controller
    {
        public async Task<IActionResult> Index()
        {
            //HttpContext.Session.Remove("token");
            //ViewBag.Message = "User logged out successfully!";
            //return View("Index");

            if (HttpContext.Session.GetString("token") == null)
            {

                return RedirectToAction("Login", "Login");

            }
            else
            {

                List<MovieItem> ItemList = new List<MovieItem>();
                using (var client = new HttpClient())
                {


                    var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                    client.DefaultRequestHeaders.Accept.Add(contentType);

                    client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
     

                    using (var response = await client.GetAsync("https://localhost:44395/api/customer/"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        ItemList = JsonConvert.DeserializeObject<List<MovieItem>>(apiResponse);
                    }
                    using (var response = await client.GetAsync("https://localhost:44395/api/customer/Genres"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        ViewBag.Genres = JsonConvert.DeserializeObject<List<Genre>>(apiResponse).ToList();
                    }
                    User user = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("user"));
                    using (var response = await client.GetAsync("https://localhost:44395/api/customer/"+user.Id))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        ViewBag.FavMovies = JsonConvert.DeserializeObject<List<MovieItem>>(apiResponse).ToList();
                    }
                    return View(ItemList);
                }
            }
        }
            //[HttpGet]
            //public ActionResult Login()
            //{
            //    return View();
            //}

            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> Login(User user)
            //{
            //    User Item = new User();
            //    using (var httpClient = new HttpClient())
            //    {
            //        StringContent content = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");
            //        var response = await httpClient.PostAsync("https://localhost:44395/api/user/Users", content);
            //        string apiResponse = await response.Content.ReadAsStringAsync();
            //        Item = JsonConvert.DeserializeObject<User>(apiResponse);

            //        StringContent content1 = new StringContent(JsonConvert.SerializeObject(Item), Encoding.UTF8, "application/json");
            //        using (var response1 = await httpClient.PostAsync("https://localhost:44395/api/auth/", content1))
            //        {
            //            string apiResponse1 = await response1.Content.ReadAsStringAsync();
            //            //usr = JsonConvert.DeserializeObject<UserModel>(apiResponse);

            //            //string stringData = JsonConvert.SerializeObject(usr);
            //            //var contentData = new StringContent(stringData,System.Text.Encoding.UTF8, "application/json");
            //            string stringJWT = response1.Content.ReadAsStringAsync().Result;


            //            JWT jwt = JsonConvert.DeserializeObject<JWT>(stringJWT);

            //            HttpContext.Session.SetString("token", jwt.Token);

            //            ViewBag.Message = "User logged in successfully!";
            //            return RedirectToAction("Index");

            //        }

            //    }

            //    //    HttpResponseMessage response = client.PostAsync
            //    //("/api/security", contentData).Result;
            //}


            // GET: AdminController/Details/5
            public ActionResult Details(int id)
            {
                return View();
            }

            // GET: AdminController/Create
            public async Task<IActionResult> Create()
            {
                if (HttpContext.Session.GetString("token") == null)
                {

                    return RedirectToAction("Login", "Login");

                }
                else
                {

                    using (var client = new HttpClient())
                    {


                        var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                        client.DefaultRequestHeaders.Accept.Add(contentType);

                        client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                        //   StringContent content = new StringContent(JsonConvert.SerializeObject(movieItem), Encoding.UTF8, "application/json");

                        using (var response = await client.GetAsync("https://localhost:44395/api/admin/Genres"))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            ViewBag.Genres = JsonConvert.DeserializeObject<List<Genre>>(apiResponse).ToList();
                            //var obj = JsonConvert.DeserializeObject<List<Genre>>(apiResponse);       //No Response
                            //List<SelectListItem> list = new List<SelectListItem>();
                            //foreach (var item in obj)
                            //{
                            //    list.Add(new SelectListItem { Text = item.Name, Value = item.Id.ToString() });
                            //}
                            //ViewBag.Genres = new SelectList(list,"");
                        }

                    }
                    return View();
                }
            }

            // POST: AdminController/Create
            [HttpGet]
            public async Task<IActionResult> AddToFavorites(int id)
            {
                if (HttpContext.Session.GetString("token") == null)
                {

                    return RedirectToAction("Login", "Login");

                }
                else
                {

                    MovieItem Item = new MovieItem();

                    using (var client = new HttpClient())
                    {


                        var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                        client.DefaultRequestHeaders.Accept.Add(contentType);

                        client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                        StringContent content = new StringContent(HttpContext.Session.GetString("user"), Encoding.UTF8, "application/json");

                        using (var response = await client.PutAsync("https://localhost:44395/api/customer/"+id, content))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            Item = JsonConvert.DeserializeObject<MovieItem>(apiResponse);       //No Response
                        }

                    }
                    return RedirectToAction("Index");
                }
            }




            // GET: AdminController/Edit/5
            public async Task<IActionResult> GetFavorites()
            {
                if (HttpContext.Session.GetString("token") == null)
                {

                    return RedirectToAction("Login", "Login");

                }
                else
                {

                    List<MovieItem> ItemList = new List<MovieItem>();
                    using (var client = new HttpClient())
                    {


                        var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                        client.DefaultRequestHeaders.Accept.Add(contentType);

                        client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));


                        using (var response = await client.GetAsync("https://localhost:44395/api/customer/Genres"))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            ViewBag.Genres = JsonConvert.DeserializeObject<List<Genre>>(apiResponse).ToList();
                        }
                        User user = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("user"));
                        using (var response = await client.GetAsync("https://localhost:44395/api/customer/" + user.Id))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            ItemList = JsonConvert.DeserializeObject<List<MovieItem>>(apiResponse).ToList();
                        }
                        return View(ItemList);
                    }
                }
            }

            // POST: AdminController/Edit/5
            [HttpPost]
            [ValidateAntiForgeryToken]

MovieManagement/MovieManagementApp/MovieCruiserApp/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using MovieCruiserApp.Models;
using Microsoft.AspNetCore.Http;

namespace MovieCruiserApp.Controllers
{
    public class SignupController : Controller
    {
        public IActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Signup(User user)
        {
            using (var httpClient = new HttpClient())
            {


                StringContent content1 = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");
                using (var response1 = await httpClient.PostAsync("https://localhost:44395/api/User/", content1))
                {
                    string apiResponse1 = await response1.Content.ReadAsStringAsync();
                    //usr = JsonConvert.DeserializeObject<UserModel>(apiResponse);

                    //string stringData = JsonConvert.SerializeObject(usr);
                    //var contentData = new StringContent(stringData,System.Text.Encoding.UTF8, "application/json");
                    string stringJWT = response1.Content.ReadAsStringAsync().Result;

                }
            }
            return RedirectToAction("Login", "Login");
        }
    }
}

MovieManagement/MovieManagementApp/MovieCruiserApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieCruiserApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieCruiserApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Movie List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Log Out</a>
                        </li>
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="GetFavorites">My Favorites</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MovieCruiserApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MovieManagement/MovieManagementApp/MovieCruiserApp/Views/Shared/_LoginSignupLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieCruiserApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieCruiserApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anonymous" asp-action="Index">Movie List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Log In</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Signup" asp-action="Signup">Sign Up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MovieCruiserApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>